isort: insertion_sort.c
	gcc -o isort insertion_sort.c

msort: merge_sort.c
	gcc -o msort merge_sort.c

ssort: selection_sort.c
	gcc -o ssort selection_sort.c

qsort: quicksort.c
	gcc -o qsort quicksort.c
