linkedlist: linkedlist.c
	gcc -o linkedlist linkedlist.c

stack: stack.c
	gcc -o stack stack.c linkedlist.c

bst: bst.c
	gcc -o bst bst.c

heap: heap.cpp
	g++ -o heap heap.cpp

pq: pq.cpp
	g++ -o pq pq.cpp heap.cpp
